name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make application.yml
        run: |
          mkdir -p ./backend/src/main/resources
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./backend/src/main/resources/application.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./backend

      - name: Build with Gradle
        run: ./gradlew build -x test
        working-directory: ./backend

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          # 💡 [핵심] plain이 붙지 않은 진짜 실행용 jar만 업로드
          path: backend/build/libs/*[!plain].jar
          if-no-files-found: error